[package]
name = "jetris"
version = "0.1.0"
authors = ["jotalamp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
mint = "0.5"
rand="0.7"
array2d = "0.2.1"
